Newsweek.Com Clone
Eshy10/Newsweek.com-Clone pull request #1
Opened 2020-02-14 18:45 UTC by Eshy10

## Newsweek.com Clone (Using BootStrap to create a responsive design)
- Added Navigation Bar
- Added Articles
- Added Footer
-Added design for different Screen Sizes
[Live Version](https://rawcdn.githack.com/Eshy10/Newsweek.com-Clone/f53cf7aa05afbdf8c4d6866e0bc4f3a9af19e740/index.html)

2020-02-14 20:44 UTC, pelzolga123 requested changes
Project requires changes.

2020-02-14 20:48 UTC, pelzolga123 commented on index.html
> +      <div class="card mt-5" style="max-width: 1000px; max-height:500px;">
No inline styling, please kindly move all styling to style.css

2020-02-14 20:49 UTC, pelzolga123 commented
## Hi Shola! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!
Here are things you need to change, before this project can be approved:
### Tablet version:

* [ ] Navigation bar should be aligned like original one:
![image](https://user-images.githubusercontent.com/20416431/74563811-4cb6b900-4f76-11ea-8e7b-737a1a1e2aa6.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74563827-55a78a80-4f76-11ea-9eff-08bcfd6a3b48.png)

* [ ] `Opinion` and `Latest news` sections are not displaying correctly:
![image](https://user-images.githubusercontent.com/20416431/74563966-97383580-4f76-11ea-85f4-3b278113f1e5.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74563985-a323f780-4f76-11ea-947e-22b46b4c14fc.png)

* [ ] Next part should be displayed like original:
![image](https://user-images.githubusercontent.com/20416431/74564109-eb431a00-4f76-11ea-8264-ac0276c91727.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74564084-dbc3d100-4f76-11ea-932d-f461952ea1f8.png)

* [ ] `Newsletter` section is missing header
* [ ] Footer should look more like an original:
![image](https://user-images.githubusercontent.com/20416431/74564294-6b697f80-4f77-11ea-9523-c4c1d2415766.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74564336-876d2100-4f77-11ea-98c8-8b3b71280292.png)

### Mobile version:
* [ ] Navbar is messed up a little, it should be fixed:
![image](https://user-images.githubusercontent.com/20416431/74564419-b84d5600-4f77-11ea-9100-d3a07ed40cc4.png)

* [ ] First section should be `Top story` right now you have `Featured stories` at the beginning. After `Top story` goes section `More stories`.

* [ ] `Culture and travel` should have same with as other sections:
![image](https://user-images.githubusercontent.com/20416431/74565109-28101080-4f79-11ea-9886-5198a47de203.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74564911-c64fa680-4f78-11ea-9030-9f6f52e9ef56.png)

* [ ] `More stories` section should look more like original:
![image](https://user-images.githubusercontent.com/20416431/74565233-745b5080-4f79-11ea-8301-a4fb4313048d.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74565214-6c031580-4f79-11ea-9496-98ea1173b245.png)

* Same for `Options` and `Latest news` sections, they should have bigger width and bigger images:
![image](https://user-images.githubusercontent.com/20416431/74565342-b7b5bf00-4f79-11ea-951e-7f81db820b14.png)
Original:
![image](https://user-images.githubusercontent.com/20416431/74565434-dae06e80-4f79-11ea-9cdc-5cef19baf0a4.png)

* [ ] Next section should be displayed like original:
![image](https://user-images.githubusercontent.com/20416431/74565708-7e318380-4f7a-11ea-9bce-0856e37a83ea.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74565728-8a1d4580-4f7a-11ea-929d-9b57b0e25b94.png)

* [ ] Elements in the next section should be aligned properly:
![image](https://user-images.githubusercontent.com/20416431/74565772-aa4d0480-4f7a-11ea-908c-e228eb594ffa.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74565816-bdf86b00-4f7a-11ea-8cff-233f8a1f2060.png)

* Footer should look more like original:
![image](https://user-images.githubusercontent.com/20416431/74565855-d4062b80-4f7a-11ea-9a2c-f516ee6f6b64.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74565877-de282a00-4f7a-11ea-8960-02843475976e.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-02-17 12:44 UTC, lekegitrepo commented
### Hi, @Eshy10 
great job I'm approving this project, but you can check on a few warnings indicated by the validator.
Hence, congratulation you can merge this.
good luck with your next project.

2020-02-17 12:46 UTC, lekegitrepo approved these changes

2020-02-17 12:51 UTC, merged